spring:
  application:
    name: order-sync
  batch:
    job:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/order-sync/protocol/openid-connect/certs

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${DB_USER:order_sync}
    password: ${DB_PASSWORD:order_sync_pw}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-sync-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379

app:
  file-watcher:
    incoming-dir: ./import/incoming
    processed-dir: ./import/processed
    error-dir: ./import/error
  security:
    keycloak:
      token-uri: http://localhost:8081/realms/order-sync/protocol/openid-connect/token
      client-id: order-sync-api
      client-secret: ${KEYCLOAK_CLIENT_SECRET:}
      test-username: ${KEYCLOAK_TEST_USERNAME:}
      test-password: ${KEYCLOAK_TEST_PASSWORD:}