-- Simulates the legacy ERP table (TOTVS/Progress-style).
-- This is the "source of truth" that our CDC pipeline will watch.
CREATE TABLE legacy_orders (
                               order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               customer_name VARCHAR2(150) NOT NULL,
                               product_code  VARCHAR2(50)  NOT NULL,
                               quantity      NUMBER        NOT NULL,
                               unit_price    NUMBER(12,2)  NOT NULL,
                               status        VARCHAR2(30)  DEFAULT 'PENDING' NOT NULL,
                               created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                               updated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- A couple of sample rows so we have something to sync once CDC is wired up.
INSERT INTO legacy_orders (customer_name, product_code, quantity, unit_price, status)
VALUES ('Acme Corp', 'SKU-001', 10, 49.90, 'PENDING');

INSERT INTO legacy_orders (customer_name, product_code, quantity, unit_price, status)
VALUES ('Globex Ltd', 'SKU-002', 3, 199.00, 'CONFIRMED');