-- The synced, versioned copy of order data that our microservice owns.
CREATE TABLE orders (
                        id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        legacy_order_id  NUMBER        NOT NULL,
                        customer_name    VARCHAR2(150) NOT NULL,
                        product_code     VARCHAR2(50)  NOT NULL,
                        quantity         NUMBER        NOT NULL,
                        unit_price       NUMBER(12,2)  NOT NULL,
                        status           VARCHAR2(30)  NOT NULL,
                        current_version  NUMBER        DEFAULT 1 NOT NULL,
                        synced_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                        CONSTRAINT uq_orders_legacy_order_id UNIQUE (legacy_order_id)
);

-- Full state of an order at a specific version (used to reconstruct history).
CREATE TABLE order_snapshots (
                                 id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 order_id   NUMBER NOT NULL,
                                 version    NUMBER NOT NULL,
                                 payload    CLOB   NOT NULL,
                                 created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                 CONSTRAINT fk_snapshot_order FOREIGN KEY (order_id) REFERENCES orders(id),
                                 CONSTRAINT uq_snapshot_order_version UNIQUE (order_id, version)
);

-- What changed between two consecutive versions of an order.
CREATE TABLE order_deltas (
                              id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              order_id       NUMBER NOT NULL,
                              from_version   NUMBER NOT NULL,
                              to_version     NUMBER NOT NULL,
                              changed_fields CLOB   NOT NULL,
                              created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                              CONSTRAINT fk_delta_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- Who/what changed an order, when, and through which channel.
CREATE TABLE audit_trail (
                             id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id     NUMBER NOT NULL,
                             action       VARCHAR2(20) NOT NULL,
                             source       VARCHAR2(30) NOT NULL,
                             performed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             details      CLOB,
                             CONSTRAINT fk_audit_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_audit_trail_order ON audit_trail(order_id);